<a href="https://colab.research.google.com/github/Bommisrilekkhaa/Numpy-Pandas/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=[]
a.append([1,2])
print(a)

a.extend([1,2,3])
print(a)

a.insert(0,10)
print(a)




[[1, 2]]
[[1, 2], 1, 2, 3]
[10, [1, 2], 1, 2, 3]


In [ ]:
b=(1,2,3,3)
print(b.index(1))
print(b.count(3))

0
2


In [ ]:
dic={0:[1,2,3,4],1:[2,4,6,8],2:[3,6,9]}
print(dic)

dic[3]=[1,2,3,4]
dic[3][1]=7
print(dic)

{0: [1, 2, 3, 4], 1: [2, 4, 6, 8], 2: [3, 6, 9]}
{0: [1, 2, 3, 4], 1: [2, 4, 6, 8], 2: [3, 6, 9], 3: [1, 7, 3, 4]}


In [ ]:
import numpy as np
ar=np.array([1,2,3,4,5])
print(ar.shape)

(5,)


In [ ]:
ar1=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
print(ar1)
print(ar1.shape)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
(3, 2)


In [ ]:
a1=np.arange(2,22,3)
print(a1)

[ 2  5  8 11 14 17 20]


In [ ]:
print(np.ones((2,3,4,5)))
print(np.zeros((2,3,4,5)))
print(np.random.random((2,2)))
print()

[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]
[[0.276631

In [ ]:
print(np.full(3,2),7)

[2 2 2] 7


In [ ]:
print(np.eye(4))
#identity matrix

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print(np.linspace(0.,1.,num=3))

[0.  0.5 1. ]


In [ ]:
arr=np.array([[1,2,3],[2,3,4]])
x=arr[:,:1]
y=arr[0,:1]
print(arr[:,:1])
print(arr[0,:1])
print(x.shape)
print(y.shape)



[[1]
 [2]]
[1]
(2, 1)
(1,)


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[2,3,4,5],[12,23,24,24],[12,13,14,15]])
b=np.array([0,1,2])

print(arr[np.arange(3),b]+10)

[11 13 34]


In [ ]:
print(arr[arr>10])

[12 23 24 24 12 13 14 15]


In [ ]:
ar=np.array([[1,2],[1,2]])
print(np.argmax(ar))
print(np.argmin(ar))
print(np.argsort(ar)[::-1])
print(np.where(ar>1)[0])
print(np.where(ar>=ar[np.argmax(ar)])[0])

1
0
[[0 1]
 [0 1]]
[0 1]
[0 0 1 1]


In [ ]:
print(np.append(arr,[1,2,3]))

[ 1  2  3  4  2  3  4  5 12 23 24 24 12 13 14 15  1  2  3]


In [ ]:
print(np.delete(arr,4))

[ 1  2  3  4  3  4  5 12 23 24 24 12 13 14 15]


In [ ]:
print(np.sort(ar,axis=1,kind="quicksort"))

[[1 2]
 [1 2]]


In [ ]:
%%time
x=np.sum(ar)

CPU times: user 138 µs, sys: 0 ns, total: 138 µs
Wall time: 143 µs


In [ ]:
np.add(x,y) #same shape array
np.subtract(x,y)
np.multiply(x,y)
np.divide(x,y)
np.sqrt(x)
np.dot(x,y)
x.dot(y)
x @ y

np.min(ar)
np.max(ar)
np.sum(ar)

ar.reshape(3,2)
ar.squeeze() #convert nested array to 1D #removes unwanted brackets and space [[1],[2],[3]] ===> [1,2,3] #space saving
ar.reshape(-1)
ar.reshape(-1,1) # unsqeeze

In [ ]:
a=np.array([[1],[2],[3]])
b=np.array([1,2,3])
x=a+b
print(x) #broadcasting --> extending least dimension and adding

[[2 3 4]
 [3 4 5]
 [4 5 6]]
